// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Package graph creates a StringGraph data structure for the string type
package graph

import (
	"fmt"
	"sync"
)

// Node a single node that composes the tree
type NodeStr struct {
	value string
}

func (n *NodeStr) String() string {
	return fmt.Sprintf("%v", n.value)
}

// StringGraph the Strings graph
type StringGraph struct {
	nodes []*NodeStr
	edges map[NodeStr][]*NodeStr
	lock  sync.RWMutex
}

// AddNode adds a node to the graph
func (g *StringGraph) AddNode(n *NodeStr) {
	g.lock.Lock()
	g.nodes = append(g.nodes, n)
	g.lock.Unlock()
}

// AddEdge adds an edge to the graph
func (g *StringGraph) AddEdge(n1, n2 *NodeStr) {
	g.lock.Lock()
	if g.edges == nil {
		g.edges = make(map[NodeStr][]*NodeStr)
	}
	g.edges[*n1] = append(g.edges[*n1], n2)
	g.edges[*n2] = append(g.edges[*n2], n1)
	g.lock.Unlock()
}

// AddEdge adds an edge to the graph
func (g *StringGraph) String() {
	g.lock.RLock()
	s := ""
	for i := 0; i < len(g.nodes); i++ {
		s += g.nodes[i].String() + " -> "
		near := g.edges[*g.nodes[i]]
		for j := 0; j < len(near); j++ {
			s += near[j].String() + " "
		}
		s += "\n"
	}
	fmt.Println(s)
	g.lock.RUnlock()
}
